### ISSUE TITLE
Errors on saving settings or processing transaction

### ISSUE THREAD

**Issue by DaveLindberg** [New0/direct-stripe#1]
Testing out this plugin on a wordpress site running 4.6.1. The test page is available at

https://uvacswim.org/stripe-test/

On saving the Direct Stripe/Settings, I receive the following error:

```
Warning: Illegal offset type in isset or empty in /home/content/p3pnexwpnas12_data03/00/3615300/html/wp-includes/plugin.php on line 211

Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas12_data03/00/3615300/html/wp-includes/plugin.php:211) in /home/content/p3pnexwpnas12_data03/00/3615300/html/wp-includes/pluggable.php on line 1174
```

Submitting a test donation works as expected, the transaction appears in our Stripe account. However, on page refresh, the same errors are displayed.

**Comment by New0** [comment]
Hello Dave, thank you for testing Direct Stripe.

Could you try 
- deactivating all other plugins and switch temporarily to twentyten or twentysixteen theme 
- then go to Direct Stripe/ Settings to save the settings again

If you can do that could you tell me if the warnings still show up?

Otherwise could you send me the plugins and theme you are using, i'll try to reproduce the warnings.

Regards

**Comment by DaveLindberg** [comment]
Hi,

Thanks for the response. Unfortunately, this is a live site running a
custom theme with numerous activated plugins. I really can't justify taking
the site down just to test a plugin. Sorry, but I'll just have to move on
and try another solution.

All the best,

Dave

Dave Lindberg Marketing & Design
802.282.3368 | DaveLindberg.com | twitter: @DaveLindberg
https://twitter.com/DaveLindberg | linkedin: in/DaveLindberg
https://www.linkedin.com/in/davelindberg

**Comment by New0** [comment]
Hi, 

Thank you for letting me know. If you want to try again on other project of yours don't hesitate to ask for support and give feedback!

All the best,
