### ISSUE TITLE
Error 500 but the payment is done

### ISSUE THREAD

**Issue by ynaamane** [New0/direct-stripe#103]
Hello I have a error 500 when I pay for a subscription. It say `Internal Server Error` and `no-referrer-when-downgrade`.
And the loading buton for the payment didn't change.

[https://prnt.sc/luz0zh](url)
[https://prnt.sc/luz1ez](url)

**Comment by New0** [comment]
Hello @ynaamane , thank you for using Direct Stripe.

Do you have any error logged on the stripe dashboard ? (Developers -> Logs )

Did you / Could you try with all other plugins deactivated and the default twentyseventeen theme ? And re-installing Direct Stripe ?

Could you turn on wp-debug and report any error logged ? ( https://codex.wordpress.org/Debugging_in_WordPress )

In case you need faster replies please open a ticket at https://wordpress.org/support/plugin/direct-stripe I usually reply faster.

**Comment by New0** [comment]
Hello @ynaamane , feel free to open again if you still have the issue.
