### ISSUE TITLE
no support for variable payment amount for subscription

### ISSUE THREAD

**Issue by mdagit** [New0/direct-stripe#108]
There is no support that I see for supporting a "customer specifies" amount for a subscription -- or alternatively, there is no support for a monthly subscription with a customer-specified month amount.
There also seems to be no support for the customer specifying a total amount limit either in currency or time or number of recurring payments.

**Comment by New0** [comment]
Hello @mdagit ,

As for the previous issue, these are features that go beyond the generic use intended by Direct Stripe and falls into specific needs. 

I recently made an example gist that shows how to create a plan and subscribe a user based on the amount set in a donation button at https://gist.github.com/New0/659b7398285e820cb72330f265c5122b

It was made after a user question at https://wordpress.org/support/topic/recurring-donation-subscription-with-user-set-amount/#post-11068302
