### ISSUE TITLE
Cannot read property 'currency' of undefined - Issue with direct stripe button using DIVI

### ISSUE THREAD

**Issue by ecomatt** [New0/direct-stripe#113]
Some of my buttons have stopped working - I have updated the plugin, but not using WordPress 5.0.3 yet.
the subscription buttons are working ok but not the one off payments? I can see this error in chrome?
can you shed any light please. 
url is wegive.steiner.academy

main.min.js?ver=4.9.9:1 Uncaught TypeError: Cannot read property 'currency' of undefined
    at HTMLButtonElement.<anonymous> (main.min.js?ver=4.9.9:1)
    at HTMLButtonElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLButtonElement.r.handle (jquery.js?ver=1.12.4:3)

**Comment by New0** [comment]
Hello @ecomatt , are you still having this issue ?
