### ISSUE TITLE
Color picker style

### ISSUE THREAD

**Issue by marcusig** [New0/direct-stripe#137]
Before I change anything on that, I was wondering why this style is applied here?

Removing it allows to have the color preview, which I would think is desirable for this setting?

![image](https://user-images.githubusercontent.com/11990914/65161517-fd587500-da37-11e9-88d8-f9a7b95008ab.png)

**Comment by New0** [comment]
I'm not exactly sure but I would guess that I wasn't sure how to properly return the value within .wpColorPicker() , I agree it would be cool to have the color displayed next to the option. Being within the same .wpColorPicker() or in a custom box.

**Comment by marcusig** [comment]
This looks interesting: https://gist.github.com/pvolyntsev/67acceebdbbdd55ab6a7f6e2369f099c

~~I might try it.~~

I've found something easier.

**Comment by New0** [comment]
Closed via https://github.com/New0/direct-stripe/commit/558611a45dba5e9cdab6184af2e6ecffe0381ce8
