### ISSUE TITLE
Broken image when no logo is selected

### ISSUE THREAD

**Issue by marcusig** [New0/direct-stripe#138]
When no image is selected or when removing the previous one, the logo is replaced by a broken image

![image](https://user-images.githubusercontent.com/11990914/65161963-c9ca1a80-da38-11e9-9b97-7921cb445c43.png)

The corresponding setting is also saved as `http://empty`

(@New0 I've made some changes already, which I'll split in different issues and PRs.)

**Comment by New0** [comment]
Closed via https://github.com/New0/direct-stripe/commit/7b7b59c8b0895b8bd3a1922012fa16b88da18cb1
