### ISSUE TITLE
Modal CSS should be stronger 

### ISSUE THREAD

**Issue by marcusig** [New0/direct-stripe#140]
The Front end modal uses some non-prefixed classes such as `.success` and `.error` that will inevitably get overridden by themes and other plugins, so they should have enough styling to not break the layout.

Also the z-index of `1` is going to be too low in many themes that use a fixed positioned header or other elements.

**Comment by New0** [comment]
Hello @marcusig , I agree that will probably cause issues for not declared css properties as the declared ones are prefixed with path .ds-element ( submitting/submitted ) etc... Good catch

**Comment by marcusig** [comment]
@New0 Sending a PR now.

**Comment by New0** [comment]
Closed via https://github.com/New0/direct-stripe/commit/e95bac93f53df4451b26761e5a62244400bacc4c
