### ISSUE TITLE
Adding display_amount=true to the shorcode doesn't work

### ISSUE THREAD

**Issue by marcusig** [New0/direct-stripe#144]
in `ds-modal-button.php`, `$ds_button->display_amount === true` will always be `false`, because display_amount is always set as a string, not a boolean. 

It might be the case for other boolean attributes, but didn't test them.

**Comment by New0** [comment]
Hello @marcusig , I have the display amount option working on my side, it is saved as a boolean in the update_settings() function in class-ds-api.php you can see the options set per buttons at domain.ext/wp-json/direct-stripe/v1/buttons

Could you test again the display amount option ?

**Comment by marcusig** [comment]
Hi @New0,

I tested when using `display_amount` in a shortcode. But I'll test again in the different situations.

**Comment by New0** [comment]
Thanks for the precision @marcusig that makes sense in the shortcode !

**Comment by New0** [comment]
Closed via https://github.com/New0/direct-stripe/commit/c1c4272b3a3c6408519240c346fedbcfabbdaf70
