### ISSUE TITLE
pre-process card errors not returned

### ISSUE THREAD

**Issue by marcusig** [New0/direct-stripe#152]
When there's a Stripe error (such as no credit card number or the likes) when pressing the pay button, the spinner shows, but doesn't disappear when Stripe returns the error. 

Also the `.visible` class, which is added to the `.error` container, doesn't have any styling (which results in the error staying hidden).

**Comment by New0** [comment]
Hello @marcusig could you test using the develop branch and let me know if that still happens ?

**Comment by marcusig** [comment]
Hi @New0 

I tested develop and the errors still don't show (at least the Stripe ones). [See screencast.](https://drive.google.com/file/d/1oY-3Pddk2xp2P97u7BYvOotJoL3Y79St/view?usp=sharing)

**Comment by New0** [comment]
Thanks @marcusig , did you make sure to flush the browser's cache ? If yes, could you run gulp direct-stripe task and test again please ? ( And reload page with Ctrl + F5 )

**Comment by marcusig** [comment]
@New0 I've already done that. I just looked at the related changes changes, and they don't address the issue of the **card elements** having errors, which happen before the jQuery.post. 

![image](https://user-images.githubusercontent.com/11990914/65588569-0db4a680-df88-11e9-9158-8f45ca964aac.png)

The highlighted location in the screenshot above should have something like
```
      dsProcess.classList.remove("submitting");
      dsProcess.classList.add("error");
``` 
or maybe call `displayFinalResult(...)`

**Comment by marcusig** [comment]
Otherwise in `ds-register-elements.js`, `dsProcess.classList.add("submitting");`should only be called here, instead of around L106

![image](https://user-images.githubusercontent.com/11990914/65589979-46ee1600-df8a-11e9-9f64-86f5d406d023.png)

**Comment by New0** [comment]
Hello @marcusig , thank you for testing. 
The code you mention returns the error on Card element creation failure. 
I believe we are talking about the errors returned after a transaction failure. 
This happens in  assets/public/src/js/ds-handler.js l117  
Could you check that in the code base you test with you have the diffs from https://github.com/New0/direct-stripe/pull/156/files#diff-293f6f9f47519b82ee2308c477c66dfa ( meaning did you pull develop to have latest merges ? )

You can see the changes from the Errors PR at https://github.com/New0/direct-stripe/pull/156/files

**Comment by marcusig** [comment]
@New0 Yes I pulled the latest develop, those changes are there. 

Have you tried submitting the form without filling any card info or wrong information? This is where the issue is. 

The "loading" overlay (`.processing`) is shown as soon as the form is submitted. The form elements are validated via htm5 so they'll prevent submitting, but errors in the card form don't prevent the submit event, but `resultP` will contain the card errors at that stage. 

Do try to submit with invalid card fields (e.g. empty), and you should see the issue for yourself.

**Comment by New0** [comment]
Thanks for the precision @marcusig , we were trying different issues. I didn't test empty card element yet so that makes sense but the Stripe tests number error cards should be ( I have them returned ) returned in develop... Maybe we could rename the issue "pre-process card errors not returned" I'll use that issue number as the branch to fix this.

**Comment by marcusig** [comment]
@New0 Sounds good, renamed.

**Comment by New0** [comment]
Closed via https://github.com/New0/direct-stripe/commit/76be3f7d550157c49cd356f864366c29b6563e44

@marcusig don't hesitate to reopen if this is still an issue
