### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by terry212** [New0/direct-stripe#2]
Can I configure the payment to have users enter the amount like how the donation portion is set up. I just don't want payments to show up as a donation on the backend to not get anyone confused?

**Comment by terry212** [comment]
Also which file can I configure to get the customer's billing information?

**Comment by New0** [comment]
Hello, 

For the first question : 
Do you want to change the word "donation" in WordPress admin panel? 
Without touching the plugin's code one way to "hack" that would be using a translation file...

Otherwise you can try adding a filter to your theme's file functions.php like so : 


`function directstripe_columns_filter( $columns ) {
   unset($columns['type']);
   return $columns;
   }`
`add_filter( 'manage_edit-directstripelogs_columns', 'directstripe_columns_filter', 10, 1 );`

This will remove the type column for Direct Stripe Logs.



For the second question : 
Do you want to collect the customer's billing information? 
 You would have to edit the stripe's form in /public/shortcode.php 

That would collect billing infos to see them in stripe's panel admin.

Best regards

**Comment by terry212** [comment]
Hello,

For the billing information, I wouldn't have those declared unless it is integrated into the plugin. I do not need to view it in the backend, just need that to show in the modal form when the user is making a payment.

**Comment by New0** [comment]
Hello,

I will add an option for those that need to collect billing info soon.

Meanwhile you can add : 
`data-address="true"` 
in /public/shortcode.php just between lines 15 and 16

and tell me if that's what you're looking for.

Regards

**Comment by New0** [comment]
Hello, 

I updated the plugin in WordPress with an option, to ask for billing details before payment in the modal form ( I will collect and show billing details in WordPress user panel soon).

Please test it and don't hesitate to leave a review!

**Comment by terry212** [comment]
Hello,

Thank you for everything. I will test it on my website soon.

**Comment by terry212** [comment]
Hello,

This is the error I receive upon checking the billing information checkbox:


Warning: Illegal offset type in isset or empty in ......./wp-includes/plugin.php on line 211

Warning: Cannot modify header information - headers already sent by (output started at ........../wp-includes/plugin.php:211) in ......./wp-includes/pluggable.php on line 1174

**Comment by terry212** [comment]
I deleted the plugin from the cpanel to get rid of those error codes then reinstalled it and everything seems fine. However, I got this error in test mode:

Fatal error: Class 'Stripe\Stripe' not found in ..../wp-content/plugins/direct-stripe/includes/create_donation.php on line 16

**Comment by New0** [comment]
Hello, 
Could you make sure the API key is entered without errors, no space at the end during the copy/paste process?

**Comment by terry212** [comment]
Hey,
Yea they are without error. I left them the same before the update when everything was working.

**Comment by New0** [comment]
Hi,
Do you have another Stripe plugin activated?

**Comment by terry212** [comment]
Hi,
Yes and I deactivated it and the payment works fine now. I still get this error when I change and save a settings even though it still saves whatever I edit:

Warning: Illegal offset type in isset or empty in ..../wp-includes/plugin.php on line 188

Warning: Cannot modify header information - headers already sent by (output started at ..../wp-includes/plugin.php:188) in .../wp-includes/pluggable.php on line 1179

**Comment by New0** [comment]
Hi,

Sorry for the delay, 
I didn't get these warnings on any of my environments, could i get more details like which version of php is your server running on? Or what host are you using?

**Comment by New0** [comment]
Also, if your environment allow this, could you switch to a default theme like twentytwelve for a moment and test to save a direct stripe setting? 
Pushing  the debug all the way by deactivating all other plugins would also help

Regards

**Comment by terry212** [comment]
Hi,
That is fine, it still works so that's all that matters to me. Thank you for everything.

**Comment by New0** [comment]
Ok then, don't hesitate to share any debug information in the future and take the time to leave a review!

Best regards
