### ISSUE TITLE
Blank page after payment

### ISSUE THREAD

**Issue by sdgmedia** [New0/direct-stripe#42]
Hi, the plugins is working fine except after the payment. I attached in the setting the success page (http://www.sdgdigital.com/merci/). But after the payment, it goes to a page like this:

http://www.sdgdigital.com/plan-pme35/?direct-stripe=subscription&amount=NDAyNA%3D%3D&coupon&setup_fee&capture=false&description=Les%20experts%20en%20TI&currency&success_query&error_query&success_url=http://www.sdgdigital.com/merci/&error_url&button_id=PME35&custom_role&ds-nonce=0e2d29625c

Because i am in a test mode, did i'm suppose to see something in the log?

Best Regards

**Comment by sdgmedia** [comment]
Forget it, I forgot to add the subscription on Stripe...Doh!
Workinf fine ;-)

**Comment by New0** [comment]
Hi sdgmedia, 
I'm glad you found what was missing!

As you are a github user, i recommend to check the stripe logs in Stripe's admin panel whenever you have trouble with the button. They are the best documentation!

Thank you for trying out Direct Stripe, and don't hesitate to give feedback.

Best regards
