### ISSUE TITLE
Shortcode idea to add (enhancement)

### ISSUE THREAD

**Issue by westaussie** [New0/direct-stripe#71]
Hey mate ... just found your plugin. Seems like it will do the job I want out of the box  (although not yet tried to make it work for my requirements) :-)

Any plans to add any more simple shortcodes? For example:

I'm needing a way to output (via shortcode) very simple "status" type info for a user/transaction ie in the site I'm building (a membership style site) ... the user fills in and submits the registration form with email address/name etc (essentially creating a WP user with subscriber capability/role), gets auto logged in (so has a user id etc), then fills in their profile (another form with more fields), submits that form, gets directed to a page to pay for a subscription (using your Stripe plugin), on successful "authorisation" (not capture) the site admin gets notified that the user has completed their profile and paid, they can then "approve" the user in the normal WP way by upgrading their role to Editor (or whatever), which then uses a hook to tell Stripe to capture payment/subscription.

That is the basic "flow", just looking for a way to use a shortcode that then uses the user id/email/trasaction id (stored in user meta) to output basic status from Stripe ie Date, Amount, Subscription Details and maybe a "Cancel" button that can cancel the Stripe subscription.

Would something like this be possible and also a good addition to your already awesome plugin? How would I go about leveraging the excellent foundations you have already to add that extra capability?

Cheers.

**Comment by New0** [comment]
Hello @westaussie ,

Thank you for testing Direct Stripe.

Direct Stripe currently allows to set the capture status, add roles to the user and send the email to the admin.
If I understand your process, you want to set the capture to false, set an email for the admin and then manually add a role to the user that would trigger the capture, is that correct ?

I'm far behind schedule with the enhancements I'd like to add to Direct Stripe so I can't promise any further development soon.

But you could set the capture during the role change using Stripe API -- https://stripe.com/docs/api#capture_charge --

I hope you understand,

Best,

Nico
