### ISSUE TITLE
nonce not verified from submission

### ISSUE THREAD

**Issue by brandonkal** [New0/direct-stripe#97]
Before my critique I must say I really appreciate the plugin and it has served as an excellent example of how to integrate Stripe with WP.

Looking through the code, it appears that the nonce is only checked server side.
This should be considered a security concern because it effectively negates the whole purpose of using a nonce.

This is the current plugin nonce logic:
1. nonce is created and stored with WordPress and in the $params server side array
2. nonce is sent to client page in the localization
3. nonce is never included in the AJAX POST request
4. WordPress nonce is compared against the nonce stored in the server side array.

I don't see a case above where that logic would ever result in a nonce verification failure.

**Comment by New0** [comment]
Hello @brandonkal Thank you for noticing that issue, I probably missed that point when I rewrote the plugin to process transactions via ajax, originally the process created a redirection and the nonce was passed via a url.
I'll rewrite that as soon as I can.

Thanks again

**Comment by New0** [comment]
Hello @brandonkal , looking closer, the nonce was passed to the Ajax request, maybe what was confusing is that it was in the params and extracted as a variable to be checked using wp_verify_nonce().

I rewrote this to use the check_ajax_referer() that is more appropriate.

Let me know what you think.

**Comment by brandonkal** [comment]
Okay, I see where you had it now. 👍 Personally, I'm not a fan of using extract() as it tends to create confusion on where variables are defined. As $params is also defined in ds-data, that is where I assumed it was coming from. https://github.com/New0/direct-stripe/blob/7094291f23bf3168e68d18d4614db17815ff79b8/includes/ds-data.php#L97

**Comment by New0** [comment]
Hello @brandonkal , keep in mind that what happens in the process folder is the process of an Ajax request and the php variables set in ds-data are not available anymore.
But that helped, I think it was a good thing to change the nonce verification design, thank you.
